# coding: utf-8

"""
    Grafeas API

    An API to insert and retrieve annotations on cloud artifacts.

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class LinkMetadata(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, signed=None, signatures=None):
        """
        BuildDetails - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'signed': 'LinkSignable',
            'signatures': 'list[dict(str, str)]',
        }

        self.attribute_map = {
            'signed': 'signed',
            'signatures': 'signatures'
        }

        self._signed = signed
        self._signatures = signatures

    @property
    def signed(self):
        """
        Gets the signed of this BuildDetails.
        The actual signed

        :return: The signed of this BuildDetails.
        :rtype: BuildProvenance
        """
        return self._signed

    @signed.setter
    def signed(self, signed):
        """
        Sets the signed of this BuildDetails.
        The actual signed

        :param signed: The signed of this BuildDetails.
        :type: BuildProvenance
        """

        self._signed = signed

    @property
    def signatures(self):
        """
        Gets the signatures of this BuildDetails.
        Serialized json representation of the signed, used in generating the BuildSignature in the corresponding Result. After verifying the signature, signatures can be unmarshalled and compared to the signed to confirm that it is unchanged. A base64-encoded string representation of the signed bytes is used for the signature in order to interoperate with openssl which expects this format for signature verification.  The serialized form is captured both to avoid ambiguity in how the signed is marshalled to json as well to prevent incompatibilities with future changes.

        :return: The signatures of this BuildDetails.
        :rtype: str
        """
        return self._signatures

    @signatures.setter
    def signatures(self, signatures):
        """
        Sets the signatures of this BuildDetails.
        Serialized json representation of the signed, used in generating the BuildSignature in the corresponding Result. After verifying the signature, signatures can be unmarshalled and compared to the signed to confirm that it is unchanged. A base64-encoded string representation of the signed bytes is used for the signature in order to interoperate with openssl which expects this format for signature verification.  The serialized form is captured both to avoid ambiguity in how the signed is marshalled to json as well to prevent incompatibilities with future changes.

        :param signatures: The signatures of this BuildDetails.
        :type: str
        """

        self._signatures = signatures

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
